defaults: &defaults
  working_directory: /go/src/github.com/djthorpe/gopi

version: 2

jobs:
  test:
    <<: *defaults
    docker:
      - image: circleci/golang:1.13-buster    
    steps:
      - checkout
      - run make test
  build:
    <<: *defaults
    docker:
      - image: circleci/golang:1.13-buster    
    steps:
      - checkout
      - run make install
  
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
